export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_USER = 'SET_USER';

export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE';

export const LOGOUT_REQUEST = 'USERS_LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'USERS_LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'USERS_LOGOUT_FAILURE';

export const GETALL_REQUEST = 'USERS_GETALL_REQUEST';
export const GETALL_SUCCESS = 'USERS_GETALL_SUCCESS';
export const GETALL_FAILURE = 'USERS_GETALL_FAILURE';

export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const LOCATION_CHANGES = 'LOCATION_CHANGES';

export const ALL_WORKERS_REQUEST = 'ALL_WORKERS_REQUEST';
export const ALL_WORKERS_SUCCESS = 'ALL_WORKERS_SUCCESS';
export const ALL_WORKERS_FAILURE = 'ALL_WORKERS_FAILURE';

export const HIRE_WORKER_REQUEST = 'HIRE_WORKER_REQUEST';
export const HIRE_WORKER_SUCCESS = 'HIRE_WORKER_SUCCESS';
export const HIRE_WORKER_FAILURE = 'HIRE_WORKER_FAILURE';

export const WORKER_RESPONSE_REQUEST = 'WORKER_RESPONSE_REQUEST';
export const WORKER_RESPONSE_SUCCESS = 'WORKER_RESPONSE_SUCCESS';
export const WORKER_RESPONSE_FAILURE = 'WORKER_RESPONSE_FAILURE';

export const CONFIRM_JOB_REQUEST = 'CONFIRM_JOB_REQUEST';
export const CONFIRM_JOB_SUCCESS = 'CONFIRM_JOB_SUCCESS';
export const CONFIRM_JOB_FAILURE = 'CONFIRM_JOB_FAILURE';

export const WORKER_LOGGED_OUT = 'WORKER_LOGGED_OUT';
export const WORKER_LOGGED_IN = 'WORKER_LOGGED_IN';

export const ALL_RANKS_REQUEST = 'ALL_RANKS_REQUEST';
export const ALL_RANKS_SUCCESS = 'ALL_RANKS_SUCCESS';
export const ALL_RANKS_FAILURE = 'ALL_RANKS_FAILURE';

export const RANK_REQUEST = 'RANK_REQUEST';
export const RANK_SUCCESS = 'RANK_SUCCESS';
export const RANK_FAILURE = 'RANK_FAILURE';

export const NOTIFICATIONS_REQUEST = 'NOTIFICATIONS_REQUEST';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAILURE = 'NOTIFICATIONS_FAILURE';

export const NOTIFICATION_DETAILS_REQUEST = 'NOTIFICATION_DETAILS_REQUEST';
export const NOTIFICATION_DETAILS_SUCCESS = 'NOTIFICATION_DETAILS_SUCCESS';
export const NOTIFICATION_DETAILS_FAILURE = 'NOTIFICATION_DETAILS_FAILURE';

export const NOTIFICATION_DELIVERED_REQUEST = 'NOTIFICATION_DELIVERED_REQUEST';
export const NOTIFICATION_DELIVERED_SUCCESS = 'NOTIFICATION_DELIVERED_SUCCESS';
export const NOTIFICATION_DELIVERED_FAILURE = 'NOTIFICATION_DELIVERED_FAILURE';

export const NOTIFICATION_DETAILS_CLOSED = 'NOTIFICATION_DETAILS_CLOSED';

export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const NOTIFICATION_OPENED = 'NOTIFICATION_OPENED';
