// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Projects/OnDemandService/node_modules/react');
var {Component} = React;
var ReactNative = require('c:/Projects/OnDemandService/node_modules/react-native');
var {AppRegistry} = ReactNative;
var entryPoint = require('c:/Projects/OnDemandService/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
  AppRegistry.runApplication('OnDemandService', appParameters);
});
